### ISSUE TITLE
rename artifacts

### ISSUE THREAD

**Issue by wolfram-weidel** [jeconfig/jeconfig#28]
- to org.jeconfig.*
- bundle symbolic names should only use the artifactid
- bundle symbolc names must be equal to artifact name

**Comment by wolfram-weidel** [comment]
Two possible solutions: 
- groupId=org.jeconfig, artifactId=org.jeconfig.api, bundle-symbolicName=org.jeconfig.api
  jarname=org.jeconfig.api-$version.jar
- create header in source-jar: "Eclipse-SourceBundle"

**Comment by edmund-wagner** [comment]
closed by 4de98cbc29fad468f5a13c3fadecbb947c674303: renamed modules
